apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alumno-ver-pods
  namespace: test-rbac
subjects:
- kind: ServiceAccount
  name: alumno
  namespace: test-rbac
roleRef:
  kind: Role
  name: rol-ver-pods
  apiGroup: rbac.authorization.k8s.io
