apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-alpha
  namespace: team-alpha
subjects:
- kind: ServiceAccount
  name: alpha-dev
  namespace: team-alpha
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-beta
  namespace: team-beta
subjects:
- kind: ServiceAccount
  name: beta-dev
  namespace: team-beta
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
